openapi: 3.0.0
info:
  title: Kanban API
  version: 1.0.0
servers:
  - url: http://localhost:5000
components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /signup:
    post:
      tags:
        - Auth
      summary: signup
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: email@email.com
                login: login
                senha: '123456'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - Auth
      summary: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                login: letscode
                senha: lets@123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /cards:
    post:
      tags:
        - Card
      summary: Create Card
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                conteudo: Card 3
                titulo: titulodsadasd
                lista: listaaaaaaaaaaa
      security:
        - jwtAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - Card
      summary: Get Cards
      security:
        - jwtAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /cards/{id}:
    get:
      tags:
        - Card
      summary: Get Card
      security:
        - jwtAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - Card
      summary: Delete Card
      security:
        - jwtAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - Card
      summary: Update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                titulo: titulodsadasd
                conteudo: conteudo
                lista: listaaaaaaaaaaa
      security:
        - jwtAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
